import type { Episode } from '../Player'
import { alphabeta } from './alphabeta'
import { autograd } from './autograd'
import { backpropEp } from './backprop'
import { bayes } from './bayes'
import { broadcast } from './broadcast'
import { cnn } from './cnn'
import { dilated } from './dilated'
import { ethics } from './ethics'
import { evaluate } from './evaluate'
import { gaussian } from './gaussian'
import { imagenp } from './imagenp'
import { kmeans } from './kmeans'
import { knn } from './knn'
import { otsu } from './otsu'
import { perceptron } from './perceptron'
import { xor } from './xor'

/** Animation code for every episode listed in sitemap EPISODES. */
export const EPISODE_CODE: Record<string, Episode> = { xor, bayes, backprop: backpropEp, cnn, kmeans, alphabeta, knn, perceptron, evaluate, broadcast, gaussian, dilated, imagenp, otsu, ethics, autograd }
