server {
    listen 80;
    server_name knowcs.online;
    location ^~ /.well-known/acme-challenge/ {
        root /www/sites/knowcs/acme;
    }
    location / { return 301 https://knowcs.online$request_uri; }
}

server {
    listen 443 ssl;
    http2 on;
    server_name knowcs.online;
    root /www/sites/knowcs/current;
    index index.html;
    ssl_certificate /www/sites/knowcs/ssl/fullchain.pem;
    ssl_certificate_key /www/sites/knowcs/ssl/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    gzip on;
    gzip_comp_level 6;
    gzip_vary on;
    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache";
        add_header X-Content-Type-Options "nosniff" always;
    }
}
